title: 원종필 | WON JONGPIL
description:  WEB BACKEND DEVELOPER
url: https://jpwon-1.github.io/resume/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
